wants:
  - metadata:
      name: ngrok-tunnel
      type: managed_launch
      labels:
        service: tunnel
    spec:
      params:
        launcher: process
        command: ngrok
        args: '["http", "8080"]'
        url_regex: 'Forwarding\s+(https://[^\s]+)'
        result_field: tunnel_url
