openapi: 3.0.3
info:
  title: MyWant Recipe Schema  
  description: OpenAPI specification for MyWant recipe YAML files based on actual Go implementation
  version: 1.0.0
  contact:
    name: MyWant
    url: https://github.com/onelittlenightmusic/MyWant

components:
  schemas:
    # Root recipe object
    GenericRecipe:
      type: object
      description: Root recipe object for MyWant recipes
      required:
        - recipe
      properties:
        recipe:
          $ref: '#/components/schemas/RecipeContent'
      additionalProperties: false
    
    # Recipe content with metadata, parameters, wants, and results
    RecipeContent:
      type: object
      description: Recipe content containing parameters, wants, and result specifications
      properties:
        metadata:
          $ref: '#/components/schemas/GenericRecipeMetadata'
        parameters:
          type: object
          description: Recipe parameters with default values (map[string]interface{})
          additionalProperties: true
          example:
            prefix: "queue-system"
            count: 1000
            rate: 10.0
            service_time: 0.1
        parameter_descriptions:
          type: object
          description: Human-readable descriptions for recipe parameters
          additionalProperties:
            type: string
          example:
            prefix: "Prefix used for naming wants"
            count: "Number of packets to generate"
        wants:
          type: array
          description: Array of recipe want definitions
          items:
            $ref: '#/components/schemas/RecipeWant'
        state:
          type: array
          description: "Coordinator-level state fields that will be added to the Target's ProvidedStateFields"
          items:
            $ref: '#/components/schemas/StateDef'
        result:
          $ref: '#/components/schemas/RecipeResult'
        finalResultField:
          type: string
          description: State field name to use as the primary result for this recipe
        example:
          $ref: '#/components/schemas/RecipeExample'
        templates:
          type: object
          description: "Legacy support for existing template formats (deprecated)"
          deprecated: true
          additionalProperties: true
      additionalProperties: false
    
    # Recipe metadata
    GenericRecipeMetadata:
      type: object
      description: Recipe metadata including name, description, version
      properties:
        name:
          type: string
          description: Recipe name
          example: "Travel Itinerary"
        description:
          type: string
          description: Recipe description
          example: "Complete travel booking coordination"
        version:
          type: string
          description: Recipe version
          example: "1.0.0"
        type:
          type: string
          description: Recipe type (travel, qnet, fibonacci, etc.)
          example: "travel"
        custom_type:
          type: string
          description: Custom type identifier for the recipe
          example: "wait time in queue system"
        category:
          type: string
          description: Recipe category
          example: "system"
      additionalProperties: false
    
    # Recipe want definition (supports both structured and flattened)
    RecipeWant:
      type: object
      description: Want definition in recipe format. Supports structured (metadata/spec) or flattened structure.
      properties:
        # Structured format (preferred)
        metadata:
          $ref: '#/components/schemas/WantMetadata'
        spec:
          $ref: '#/components/schemas/WantSpec'
        
        # Legacy flattened fields
        name:
          type: string
          description: Want name (optional, auto-generated if not provided)
          example: "my-processor"
        type:
          type: string
          description: Want type that determines processing behavior
          example: "queue"
        labels:
          type: object
          description: Key-value pairs for flexible want connections (map[string]string)
          additionalProperties:
            type: string
          example:
            role: "processor"
            category: "data-processing"
            component: "main-queue"
        params:
          type: object
          description: Want-specific parameters (map[string]interface{})
          additionalProperties: true
          example:
            count: 1000
            service_time: 0.1
        using:
          type: array
          description: Label selectors for connecting to other wants ([]map[string]string)
          items:
            type: object
            description: Label selector map
            additionalProperties:
              type: string
            example:
              role: "source"
        requires:
          type: array
          description: Agent capability requirements
          items:
            type: string
        recipeAgent:
          type: boolean
          description: If true, enables auto-connection logic for this want
      additionalProperties: false
    
    # Recipe result specification (new array format)
    RecipeResult:
      type: array
      description: Array of result specifications with JSON path syntax for extracting metrics
      minItems: 1
      items:
        $ref: '#/components/schemas/RecipeResultSpec'
      example:
        - want_name: "queue-primary"
          stat_name: ".average_wait_time"
          description: "Average wait time in primary stream queue"
        - want_name: "queue-secondary"
          stat_name: ".average_wait_time"
          description: "Average wait time in secondary stream queue"
        - want_name: "queue-final"
          stat_name: "."
          description: "All metrics from final queue"
    
    # Recipe result specification for individual metrics
    RecipeResultSpec:
      type: object
      description: Specification for computing results from a specific want and stat
      required:
        - want_name
      properties:
        want_name:
          type: string
          description: Name of the want to collect results from
          example: "sink"
        state_field:
          type: string
          description: Name of the state field to use for result computation
          example: "reminder_phase"
        stat_name:
          type: string
          description: JSON path expression for extracting stat values. Use '.' for all stats, or '.field_name' for specific fields (e.g., '.' for all stats, '.average_wait_time' for specific field)
          example: ".average_wait_time"
          pattern: "^\\.$|^\\.[a-zA-Z_][a-zA-Z0-9_]*$"
        description:
          type: string
          description: Human-readable description of this result metric
          example: "Total items processed through the queue system"
      additionalProperties: false

    # Want metadata (structured)
    WantMetadata:
      type: object
      description: Want identification and classification info
      properties:
        id:
          type: string
          description: Unique identifier for the want
        name:
          type: string
          description: Human-readable name
        type:
          type: string
          description: Want type identifier
        labels:
          type: object
          description: Metadata labels for connection and classification
          additionalProperties:
            type: string
        orderKey:
          type: string
          description: Fractional index for custom ordering
      additionalProperties: false

    # Want specification (structured)
    WantSpec:
      type: object
      description: Desired state configuration for a want
      properties:
        params:
          type: object
          description: Want-specific parameters
          additionalProperties: true
        using:
          type: array
          description: Label selectors for connections
          items:
            type: object
            additionalProperties:
              type: string
        recipe:
          type: string
          description: Path to recipe file if this is a composite want
        requires:
          type: array
          description: Agent capability requirements
          items:
            type: string
        when:
          type: array
          description: Conditional execution rules
          items:
            $ref: '#/components/schemas/WhenSpec'
        finalResultField:
          type: string
          description: State field name to use as the primary result
      additionalProperties: false

    # When rule specification
    WhenSpec:
      type: object
      description: Conditional rule for want execution or state transitions
      required:
        - state
        - operator
        - value
      properties:
        state:
          type: string
          description: State key to monitor
        operator:
          type: string
          description: Comparison operator
          enum: [eq, ne, gt, gte, lt, lte, contains, exists]
        value:
          description: Value to compare against
      additionalProperties: false

    # State field definition
    StateDef:
      type: object
      description: State field definition for coordinator-level states
      required:
        - name
        - description
        - type
      properties:
        name:
          type: string
          description: State field name
          pattern: '^[a-z][a-z0-9_]*$'
        description:
          type: string
          description: State field description
        type:
          type: string
          description: State field type (int, float64, string, bool, map, etc.)
        persistent:
          type: boolean
          description: Whether state persists across restarts
          default: false
        initialValue:
          description: Initial value
        example:
          description: Example value
      additionalProperties: false

    # Recipe example for one-click deployment
    RecipeExample:
      type: object
      description: Example deployment configuration
      properties:
        wants:
          type: array
          description: Wants to deploy in the example
          items:
            $ref: '#/components/schemas/RecipeWant'
      additionalProperties: false

paths: {}  # No REST API paths, this is just for schema validation