wants:
  - metadata:
      name: dynamic travel planner
      type: dynamic travel change
      labels:
        role: dynamic-travel-planner
    spec:
      params:
        prefix: dynamic-travel
        display_name: "Dynamic Travel Itinerary with Flight"
        flight_type: "business class"
        flight_duration: 12.0
        restaurant_type: "fine dining"
        hotel_type: "luxury"
        buffet_type: "international"
        dinner_duration: 2.0
