// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: engine/src/proto/agent_service.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteRequest contains parameters for agent execution
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WantId        string                 `protobuf:"bytes,1,opt,name=want_id,json=wantId,proto3" json:"want_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	WantState     map[string]string      `protobuf:"bytes,4,rep,name=want_state,json=wantState,proto3" json:"want_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CallbackUrl   string                 `protobuf:"bytes,6,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_engine_src_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetWantId() string {
	if x != nil {
		return x.WantId
	}
	return ""
}

func (x *ExecuteRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *ExecuteRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ExecuteRequest) GetWantState() map[string]string {
	if x != nil {
		return x.WantState
	}
	return nil
}

func (x *ExecuteRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

// ExecuteResponse contains agent execution results
type ExecuteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "completed", "failed"
	StateUpdates    map[string]string      `protobuf:"bytes,2,rep,name=state_updates,json=stateUpdates,proto3" json:"state_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_engine_src_proto_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteResponse) GetStateUpdates() map[string]string {
	if x != nil {
		return x.StateUpdates
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

// MonitorRequest starts a monitoring agent
type MonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WantId        string                 `protobuf:"bytes,1,opt,name=want_id,json=wantId,proto3" json:"want_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,3,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	WantState     map[string]string      `protobuf:"bytes,4,rep,name=want_state,json=wantState,proto3" json:"want_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorRequest) Reset() {
	*x = MonitorRequest{}
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorRequest) ProtoMessage() {}

func (x *MonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorRequest.ProtoReflect.Descriptor instead.
func (*MonitorRequest) Descriptor() ([]byte, []int) {
	return file_engine_src_proto_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *MonitorRequest) GetWantId() string {
	if x != nil {
		return x.WantId
	}
	return ""
}

func (x *MonitorRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *MonitorRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *MonitorRequest) GetWantState() map[string]string {
	if x != nil {
		return x.WantState
	}
	return nil
}

// MonitorResponse confirms monitor start
type MonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorId     string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "started", "failed"
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorResponse) Reset() {
	*x = MonitorResponse{}
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorResponse) ProtoMessage() {}

func (x *MonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorResponse.ProtoReflect.Descriptor instead.
func (*MonitorResponse) Descriptor() ([]byte, []int) {
	return file_engine_src_proto_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *MonitorResponse) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

func (x *MonitorResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MonitorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StopMonitorRequest stops a monitor
type StopMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorId     string                 `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMonitorRequest) Reset() {
	*x = StopMonitorRequest{}
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMonitorRequest) ProtoMessage() {}

func (x *StopMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMonitorRequest.ProtoReflect.Descriptor instead.
func (*StopMonitorRequest) Descriptor() ([]byte, []int) {
	return file_engine_src_proto_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *StopMonitorRequest) GetMonitorId() string {
	if x != nil {
		return x.MonitorId
	}
	return ""
}

// StopMonitorResponse confirms monitor stop
type StopMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "stopped"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMonitorResponse) Reset() {
	*x = StopMonitorResponse{}
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMonitorResponse) ProtoMessage() {}

func (x *StopMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_src_proto_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMonitorResponse.ProtoReflect.Descriptor instead.
func (*StopMonitorResponse) Descriptor() ([]byte, []int) {
	return file_engine_src_proto_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *StopMonitorResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_engine_src_proto_agent_service_proto protoreflect.FileDescriptor

const file_engine_src_proto_agent_service_proto_rawDesc = "" +
	"\n" +
	"$engine/src/proto/agent_service.proto\x12\fmywant.agent\"\x90\x03\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\awant_id\x18\x01 \x01(\tR\x06wantId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12J\n" +
	"\n" +
	"want_state\x18\x04 \x03(\v2+.mywant.agent.ExecuteRequest.WantStateEntryR\twantState\x12@\n" +
	"\x06params\x18\x05 \x03(\v2(.mywant.agent.ExecuteRequest.ParamsEntryR\x06params\x12!\n" +
	"\fcallback_url\x18\x06 \x01(\tR\vcallbackUrl\x1a<\n" +
	"\x0eWantStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12T\n" +
	"\rstate_updates\x18\x02 \x03(\v2/.mywant.agent.ExecuteResponse.StateUpdatesEntryR\fstateUpdates\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x04 \x01(\x03R\x0fexecutionTimeMs\x1a?\n" +
	"\x11StateUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x0eMonitorRequest\x12\x17\n" +
	"\awant_id\x18\x01 \x01(\tR\x06wantId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12!\n" +
	"\fcallback_url\x18\x03 \x01(\tR\vcallbackUrl\x12J\n" +
	"\n" +
	"want_state\x18\x04 \x03(\v2+.mywant.agent.MonitorRequest.WantStateEntryR\twantState\x1a<\n" +
	"\x0eWantStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x0fMonitorResponse\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"3\n" +
	"\x12StopMonitorRequest\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\tR\tmonitorId\"-\n" +
	"\x13StopMonitorResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xf7\x01\n" +
	"\fAgentService\x12F\n" +
	"\aExecute\x12\x1c.mywant.agent.ExecuteRequest\x1a\x1d.mywant.agent.ExecuteResponse\x12K\n" +
	"\fStartMonitor\x12\x1c.mywant.agent.MonitorRequest\x1a\x1d.mywant.agent.MonitorResponse\x12R\n" +
	"\vStopMonitor\x12 .mywant.agent.StopMonitorRequest\x1a!.mywant.agent.StopMonitorResponseB!Z\x1fmywant/engine/src/proto/agentpbb\x06proto3"

var (
	file_engine_src_proto_agent_service_proto_rawDescOnce sync.Once
	file_engine_src_proto_agent_service_proto_rawDescData []byte
)

func file_engine_src_proto_agent_service_proto_rawDescGZIP() []byte {
	file_engine_src_proto_agent_service_proto_rawDescOnce.Do(func() {
		file_engine_src_proto_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_src_proto_agent_service_proto_rawDesc), len(file_engine_src_proto_agent_service_proto_rawDesc)))
	})
	return file_engine_src_proto_agent_service_proto_rawDescData
}

var file_engine_src_proto_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_engine_src_proto_agent_service_proto_goTypes = []any{
	(*ExecuteRequest)(nil),      // 0: mywant.agent.ExecuteRequest
	(*ExecuteResponse)(nil),     // 1: mywant.agent.ExecuteResponse
	(*MonitorRequest)(nil),      // 2: mywant.agent.MonitorRequest
	(*MonitorResponse)(nil),     // 3: mywant.agent.MonitorResponse
	(*StopMonitorRequest)(nil),  // 4: mywant.agent.StopMonitorRequest
	(*StopMonitorResponse)(nil), // 5: mywant.agent.StopMonitorResponse
	nil,                         // 6: mywant.agent.ExecuteRequest.WantStateEntry
	nil,                         // 7: mywant.agent.ExecuteRequest.ParamsEntry
	nil,                         // 8: mywant.agent.ExecuteResponse.StateUpdatesEntry
	nil,                         // 9: mywant.agent.MonitorRequest.WantStateEntry
}
var file_engine_src_proto_agent_service_proto_depIdxs = []int32{
	6, // 0: mywant.agent.ExecuteRequest.want_state:type_name -> mywant.agent.ExecuteRequest.WantStateEntry
	7, // 1: mywant.agent.ExecuteRequest.params:type_name -> mywant.agent.ExecuteRequest.ParamsEntry
	8, // 2: mywant.agent.ExecuteResponse.state_updates:type_name -> mywant.agent.ExecuteResponse.StateUpdatesEntry
	9, // 3: mywant.agent.MonitorRequest.want_state:type_name -> mywant.agent.MonitorRequest.WantStateEntry
	0, // 4: mywant.agent.AgentService.Execute:input_type -> mywant.agent.ExecuteRequest
	2, // 5: mywant.agent.AgentService.StartMonitor:input_type -> mywant.agent.MonitorRequest
	4, // 6: mywant.agent.AgentService.StopMonitor:input_type -> mywant.agent.StopMonitorRequest
	1, // 7: mywant.agent.AgentService.Execute:output_type -> mywant.agent.ExecuteResponse
	3, // 8: mywant.agent.AgentService.StartMonitor:output_type -> mywant.agent.MonitorResponse
	5, // 9: mywant.agent.AgentService.StopMonitor:output_type -> mywant.agent.StopMonitorResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_engine_src_proto_agent_service_proto_init() }
func file_engine_src_proto_agent_service_proto_init() {
	if File_engine_src_proto_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_src_proto_agent_service_proto_rawDesc), len(file_engine_src_proto_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_src_proto_agent_service_proto_goTypes,
		DependencyIndexes: file_engine_src_proto_agent_service_proto_depIdxs,
		MessageInfos:      file_engine_src_proto_agent_service_proto_msgTypes,
	}.Build()
	File_engine_src_proto_agent_service_proto = out.File
	file_engine_src_proto_agent_service_proto_goTypes = nil
	file_engine_src_proto_agent_service_proto_depIdxs = nil
}
