// Builds dist/<browser>-extension/ — Manifest V3 extensions that start the
// Web Want Inspector via a toolbar-icon click instead of a bookmarklet.
// Exists because bookmarklets (see build-standalone-overlay.js) inject a
// <script src="http://localhost:8080/...">, which CSP-strict sites (x.com
// etc.) block outright across every relevant CSP directive — verified via
// CDP. A content script's own DOM/script injection bypasses page CSP
// entirely, but its own fetch() would still inherit the page's connect-src,
// so this splits work the same way the validated prototype did: content.js
// only touches the DOM, and the background service worker (its own
// extension-scheme origin, unaffected by the page's CSP) does the actual
// network calls to mywant, relayed via chrome.runtime.sendMessage.
//
// Chrome, Firefox, and Safari (16.4+) all support the same chrome.* API
// surface this uses (action/scripting/alarms/runtime/storage/tabs/
// permissions), so background.js/options.html/options.js/content.js are
// shared verbatim across all three — only manifest.json genuinely differs
// per browser (see webext-src/manifest.*.json). Safari additionally needs
// wrapping as a native app via `make build-safari-extension`
// (xcrun safari-web-extension-converter), which takes dist/chrome-extension
// as its input since Safari accepts the same Chrome-style MV3 manifest.
//
// Pulls the compiled webInspectorOverlayCore via require() (not
// text-scraping dist/*.js), same as build-standalone-overlay.js, so this can
// never silently drift from what the CDP path and the bookmarklet run.
const fs = require('fs');
const path = require('path');
const { webInspectorOverlayCore } = require('./dist/webInspectorOverlayCore.js');

const coreSrc = webInspectorOverlayCore.toString();

const contentJs = `// AUTO-GENERATED by build-webext.js — do not edit directly.
// Source of truth: webInspectorOverlayCore.ts
(function () {
  var __webInspectorOverlayCore = ${coreSrc};

  // Relays fetch() through the background service worker (see
  // background.js) so requests to mywant aren't subject to this page's CSP
  // connect-src. AbortSignal isn't structured-cloneable across
  // chrome.runtime.sendMessage, so it's dropped here on purpose — the one
  // caller that passes one (suggestNameUrl's speculative-naming fetch in
  // webInspectorOverlayCore.ts) already guards against a late response
  // clobbering user input via its own "document.activeElement !== inp"
  // check, so losing real cancellation has no visible effect.
  function extensionFetch(url, init) {
    var cleanInit = init ? { method: init.method, headers: init.headers, body: init.body } : {};
    return new Promise(function (resolve, reject) {
      chrome.runtime.sendMessage({ type: 'MYWANT_FETCH', url: url, init: cleanInit }, function (res) {
        if (chrome.runtime.lastError) { reject(new Error(chrome.runtime.lastError.message)); return; }
        if (!res || res.error) { reject(new Error((res && res.error) || 'extension relay failed')); return; }
        resolve(new Response(res.body, { status: res.status, statusText: res.statusText }));
      });
    });
  }

  chrome.runtime.sendMessage({ type: 'MYWANT_API_ORIGIN' }, function (originRes) {
    var apiBase = (originRes && originRes.origin) || 'http://localhost:8080';
    extensionFetch(apiBase + '/api/v1/web-wants/active-inspection?url=' + encodeURIComponent(location.href))
      .then(function (r) {
        if (!r.ok) return r.json().then(function (d) { throw new Error(d.error || ('HTTP ' + r.status)); });
        return r.json();
      })
      .then(function (d) {
        __webInspectorOverlayCore({
          webhookUrl: d.done_webhook_url,
          suggestNameUrl: d.suggest_name_url,
          myCharacterId: d.character_id,
          myColor: d.color,
          myAvatar: d.avatar,
          existingMarks: d.existing_marks || [],
          navElements: d.nav_elements || [],
          fetchImpl: extensionFetch,
        });
      })
      .catch(function (e) {
        var banner = document.createElement('div');
        banner.style.cssText = 'position:fixed;top:12px;left:50%;transform:translateX(-50%);background:#1e293b;color:#f87171;padding:10px 16px;border-radius:8px;font:13px system-ui,sans-serif;z-index:2147483647;box-shadow:0 8px 24px rgba(0,0,0,.4);border:1px solid #475569;max-width:80vw;text-align:center';
        banner.textContent = 'Web Want Inspector: ' + e.message + ' — mywantサーバーに接続できません。サーバーが起動しているか確認してください。';
        document.body.appendChild(banner);
        setTimeout(function () { banner.remove(); }, 6000);
      });
  });
})();
`;

const srcDir = path.join(__dirname, 'webext-src');
const sharedStaticFiles = ['background.js', 'options.html', 'options.js'];

const browsers = [
  { name: 'chrome', manifest: 'manifest.chrome.json' },
  { name: 'firefox', manifest: 'manifest.firefox.json' },
];

for (const { name, manifest } of browsers) {
  const outDir = path.join(__dirname, 'dist', `${name}-extension`);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'content.js'), contentJs);
  fs.copyFileSync(path.join(srcDir, manifest), path.join(outDir, 'manifest.json'));
  for (const file of sharedStaticFiles) {
    fs.copyFileSync(path.join(srcDir, file), path.join(outDir, file));
  }
  console.log('[build-webext] wrote', outDir);
}
